// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSlIjMMh1VCOb5RVS_QwAJdqtlB_z_9LI',
    appId: '1:219912620379:web:8af07302590d31dca9727e',
    messagingSenderId: '219912620379',
    projectId: 'flutternew-14d48',
    authDomain: 'flutternew-14d48.firebaseapp.com',
    storageBucket: 'flutternew-14d48.appspot.com',
    measurementId: 'G-RKFD2NESSK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD54xqjWQcQ_0DF1KPB_Q6kMik6stDZV9o',
    appId: '1:219912620379:android:fb2bc59f99c293fda9727e',
    messagingSenderId: '219912620379',
    projectId: 'flutternew-14d48',
    storageBucket: 'flutternew-14d48.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMVd9ZsbjH_upZzJZ_kBFm_TcygMeLRjE',
    appId: '1:219912620379:ios:dd875dcf6a295175a9727e',
    messagingSenderId: '219912620379',
    projectId: 'flutternew-14d48',
    storageBucket: 'flutternew-14d48.appspot.com',
    iosBundleId: 'com.example.flutterweb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMVd9ZsbjH_upZzJZ_kBFm_TcygMeLRjE',
    appId: '1:219912620379:ios:dd875dcf6a295175a9727e',
    messagingSenderId: '219912620379',
    projectId: 'flutternew-14d48',
    storageBucket: 'flutternew-14d48.appspot.com',
    iosBundleId: 'com.example.flutterweb',
  );
}
